### ISSUE TITLE
Only check the first commit message

### ISSUE THREAD

**Issue by michaelschuett-tomtom** [tomtom-international/commisery#29]
Hey does any way exist to only check the first commit message currently? Since most repositories that I work our of require a squash and merge only the first commit message is relevant and even at that you are able to change the commit message in Github at merge time.

I have always been in the habit of one commit per PR and just amend to it however I find that often people end up with lots of commits on their branch before merging and then have to rebase to get CI passing. Do you have a recommended workflow so you don't have to repeat the same commit message for every commit on a branch or would you accept a PR to make this a configurable option?

**Comment by jstmlr** [comment]
Hi Michael,

[`commisery`](https://github.com/tomtom-international/commisery) and [`commisery-action`](https://github.com/tomtom-international/commisery-action) are primarily designed for a merge commit workflow, so there is no feature that only looks at a subset of the commits.

If you use the PR title to generate the squash merge commit, you could configure `commisery-action` to disable commit checking and just enable `validate-pull-request`, which only validates the PR title.

```yaml
      - name: Check for Conventional Commit compliance
        uses: tomtom-international/commisery-action@v3
        with:
          token: ${{ github.token }}
          validate-pull-request: true
          validate-commits: false
```

Another option would be to squash the changes as needed into one commit before opening the PR, and, once the PR is open, utilizing [fixup commits](https://git-scm.com/docs/git-commit/2.31.0#Documentation/git-commit.txt---fixupltcommitgt) for addressing review comments; they are ignored by both `commisery` and `commisery-action`.

Hope this helps!
